-- 주석
-- 실행 단축키 : F9
-- 계정이름 앞에 C## 생략 코드 ;
-- ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;


-- 사용자 생성
CREATE USER ORA_USER IDENTIFIED BY 1111;

-- 권한부여 : 접근권한, 리소스 권한, DB생성권한
GRANT CONNECT, RESOURCE, DBA TO ORA_USER;

-- 권한해제 : 
REVOKE CONNECT, RESOURCE, DBA FROM ORA_USER;

-- 사용자 계정 삭제
DROP USER ORA_USER;

CREATE USER ORA_USER IDENTIFIED BY 1111;
GRANT CONNECT,RESOURCE,DBA TO ORA_USER;