# Generated by Django 5.1.3 on 2024-11-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hobby',
            field=models.CharField(default='없음', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(default=1),
        ),
    ]
