# Generated by Django 5.1.3 on 2024-11-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=50)),
                ('mdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
